version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile.back
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      dockerfile: Dockerfile.front
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend

  database:
       image: 'mariadb:10.3'
       container_name: database
       restart: always
       environment:
          MYSQL_USER: backend
          MYSQL_PASSWORD: 123poi
          MYSQL_DATABASE: my_database
          MYSQL_ROOT_PASSWORD: rootpassword
